site_name: Blog
site_url: https://www.oitswilliam.com/blog

theme:
  name: material
  custom_dir: overrides
  features:

markdown_extensions:
  - footnotes
  - abbr
  - admonition
  - attr_list
plugins:
    - blog:
        blog_dir: .
        archive_date_format: MMMM yyyy
        archive_url_date_format: yyyy/MM
        post_readtime: false
        draft_on_serve: false
        draft_if_future_date: true
    - search
    - social
    - tags
extra_css:
  - stylesheets/extra.css

copyright: |
    Copyright &copy; 2024- Oitswilliam Pang. All rights reserved.
